### PR TITLE
Modularizing bo-android

### PR DESCRIPTION
**Pull request by d3xter**
So here is my try on modularizing the app.

I've added BOApplication, which is created before any BroadcastReceiver/Activity/Service is started
and lives as long as any part of the app is running.

So the BOApplication class is responsible for creating all singleton handlers in the app.
The other parts of the app just retrieve the specific handlers from the BOApplication object and doesnt have to care about initializing them. So we have a single instance of a handler in the app.

Thinking forward:
One way to use RxAndroid is, that e.g. the LocationHandler has a "val locationObservable: Observable<Location>". Another object can get the observable with "BOApplication.instance.locationHandler.locationObservable"

Also alot of code which doesnt belong into the AppService has been moved out to the appropriate places

### CODE REVIEW

**Comment by d3xter** [comment]
We could also place the handlers inside the companion object and get the instance with "BOApplication.locationHandler". Think that way its more concise

**Comment by wuan** [comment]
That sounds good.

**Comment by wuan** [comment]
There seems to be a problem with the buttons for history browsing. I'm just looking into it.

**Comment by d3xter** [comment]
History-Buttons after rotation are working now on Android 6.0.1.
Is it working for older version now?

**Comment by d3xter** [comment]
Just did some testing.

After switching the LocationProvider, the "xx/60" seconds text at the top of the MapActivity stopped and it seems like no new data is retrieved

**Comment by d3xter** [comment]
The problem was, that the consumers inside Main were unregistered in onStop(), but wasnt re-registered when the activity was shown again. Fixed now.

**Comment by d3xter** [comment]
Have you found any other bugs with this PR?

If not, I think its ready to be merged

**Pull request merged**
